export interface Project {
  id: string;
  slug: string;
  title: string;
  category: 'Product Management' | 'UI/UX Design' | 'Data & AI' | 'Others';
  subject?: string;
  competition?: string;
  shortDescription: string;
  fullDescription: string;
  gradient: string;
  tags: string[];
  challenge: string;
  solution: string;
  impact: string;
  tools: string[];
  year: string;
  date?: string;
  documentLink?: string;
  deckLink?: string;
  certificationLink?: string;
  figmaLink?: string;
  githubLink?: string;
  sourceCodeLink?: string;
  previewImage?: string;
}

export const projects: Project[] = [
  {
    id: '1',
    slug: 'talentsync',
    title: 'TalentSync',
    category: 'Product Management',
    subject: 'IF2050 Basic Software Engineering',
    shortDescription: 'Artist and Staff Management System for entertainment agencies. Minimizes scheduling conflicts, enhances performance evaluation transparency, and ensures balanced team management.',
    fullDescription: 'TalentSync is a comprehensive Artist and Staff Management System designed to help entertainment agencies efficiently manage artist schedules, evaluate performance, and coordinate staff operations. The platform serves as a centralized system accessible to managers, artists, and operational staff, with a strong focus on data security, cross-device accessibility, and user-friendly design.',
    gradient: 'from-emerald-600 to-teal-800',
    tags: ['Product Strategy', 'Operations', 'Management'],
    challenge: 'Entertainment agencies struggled with managing complex artist schedules, performance evaluations, and staff coordination across multiple teams, leading to scheduling conflicts and lack of transparency.',
    solution: 'Built a centralized management system with role-based access (Managers, Artists, Staff), integrated scheduling calendar with conflict detection, performance evaluation metrics, and comprehensive user management features.',
    impact: 'Streamlined scheduling operations, improved performance transparency, reduced scheduling conflicts, and provided a unified platform for cross-team coordination accessible across devices.',
    tools: ['Java', 'Gradle', 'JavaFX', 'Azure SQL', 'CSS'],
    year: '2025',
    date: '10/03/2025 - 20/06/2025',
    documentLink: 'https://drive.google.com/file/d/1xyqbUqVssxsu6WoCTkyPUlUT1h_2Hlot/view?usp=sharing',
    githubLink: 'https://github.com/persadaramiiza/IF2050-2025-K1K-TalentSync',
    previewImage: '/talentsync-preview-v3.png',
  },
  {
    id: '2',
    slug: 'duh-baking-business-operational-analysis',
    title: 'Business and Operational Analysis of Duh Baking Studio',
    category: 'Product Management',
    subject: 'II2221 Enterprise Needs Analysis',
    shortDescription: 'Comprehensive business and operational analysis to improve scheduling, staff management, and workflow efficiency through digital solutions.',
    fullDescription: 'Conducted a comprehensive business and operational analysis of Duh Baking Studio to identify inefficiencies in scheduling, staff management, and overall workflow. Proposed system improvements and digital solutions to enhance operational efficiency, streamline processes, and support better decision-making.',
    gradient: 'from-teal-600 to-cyan-800',
    tags: ['Business Analysis', 'Operations', 'Improvement'],
    challenge: 'Operations relied on fragmented manual processes that created inefficiencies in scheduling, team coordination, and daily workflow visibility.',
    solution: 'Mapped current operations, identified pain points, and recommended a digital operating model with standardized workflows, role clarity, and operational dashboards.',
    impact: 'Delivered actionable recommendations to improve process efficiency, reduce operational bottlenecks, and support faster managerial decision-making.',
    tools: ['Process Mapping', 'Gap Analysis', 'Root Cause Analysis', 'SWOT Analysis', 'Workflow Design'],
    year: '2025',
    date: '16/03/2025 - 14/06/2025',
    documentLink: 'https://drive.google.com/file/d/19NHnjG7ivbKK5bD4N-RfdluE8ecs2tjY/view?usp=sharing',
    deckLink: 'https://drive.google.com/file/d/1aLXd910PsQHiBapteGHZbKOnQEg-wwFQ/view?usp=sharing',
    previewImage: '/duh-baking-business-operational-analysis.png',
  },
  {
    id: '3',
    slug: 'smart-production-system-design-duh-baking-studio',
    title: 'Smart Production System Design for Duh Baking Studio',
    category: 'Product Management',
    subject: 'II3130 Enteprise Architecture',
    shortDescription: 'Designed enterprise architecture integrating internal and third-party systems to improve production flow, data flow, and operational scalability.',
    fullDescription: 'Designed an enterprise architecture solution for Duh Baking Studio by integrating multiple systems, including web platforms and third-party services, to improve data flow, production processes, and operational efficiency. Focused on aligning business, data, application, and technology layers to support scalable and secure digital transformation.',
    gradient: 'from-emerald-700 to-teal-900',
    tags: ['Enterprise Architecture', 'System Design', 'Integration'],
    challenge: 'Business and production processes were not fully connected across systems, creating data silos and slower operational execution.',
    solution: 'Designed an end-to-end enterprise architecture blueprint covering business, data, application, and technology layers with clear integration points.',
    impact: 'Provided a scalable and secure transformation blueprint to improve cross-system visibility, process consistency, and long-term digital readiness.',
    tools: ['Stakeholder Mapping', 'Value Chain', 'Value Stream', 'Business Interaction Matrix', 'BPMN', 'Environments & Location Diagram', 'Platform Decomposition Diagram', 'Processing Diagram', 'Archimate'],
    year: '2025',
    date: '02/10/2025 - 11/12/2025',
    deckLink: 'https://drive.google.com/file/d/1Y-3vU1xLusqnZvLWE2NPFq5YCGoTdctV/view?usp=sharing',
    previewImage: '/duh-baking-smart-production-system-design.png',
  },
  {
    id: '4',
    slug: 'sevenfit-well-strategy',
    title: 'Revolutionizing Sevenfit with W.E.L.L: A Strategy for Wellness, Engagement Loyalty, and Lifestyle',
    category: 'Product Management',
    competition: 'StudentxCEOs 3rd Youth Leader Summit Business Case Competition 2024',
    shortDescription: 'Built a strategic business case with data-driven recommendations to improve operations, resource utilization, and sustainable growth.',
    fullDescription: 'Developed a business case and strategic solution in collaboration with Sevenpreneur to address operational challenges by analyzing existing processes and identifying key improvement opportunities. Proposed a structured approach to enhance efficiency, optimize resource utilization, and support sustainable business growth through data-driven decision-making.',
    gradient: 'from-lime-700 to-emerald-900',
    tags: ['Business Case', 'Growth Strategy', 'Optimization'],
    challenge: 'The business needed clearer prioritization and operational structure to improve efficiency while sustaining growth in a competitive market.',
    solution: 'Developed a structured strategy with measurable initiatives, operational optimization ideas, and decision-support recommendations.',
    impact: 'Produced a practical strategy package to improve execution quality, optimize resource allocation, and strengthen long-term growth direction.',
    tools: ['Business Case Analysis', 'Problem Prioritization', 'Process Improvement', 'KPI Planning', 'Implementation Roadmap'],
    year: '2024',
    date: '01/07/2025 - 12/07/2024',
    documentLink: 'https://drive.google.com/file/d/1OL8ip3OmVwO2fwOykTjlnBHleq4o6IIb/view?usp=sharing',
    certificationLink: 'https://drive.google.com/file/d/1gKMtefHDw2bmLscWH6YfC6WihWfK-M45/view?usp=sharing',
    previewImage: '/sevenfit-well-strategy.png',
  },
  {
    id: '5',
    slug: 'boosting-digital-transformation-grab-sme',
    title: 'BOOSTing Digital Transformation: Grab\'s Strategic Path to SME Success',
    category: 'Product Management',
    competition: 'Business Case Competition #UMKMGoesDigital by GrabMerchant 2024',
    shortDescription: 'Analyzed MSME digital adoption barriers and proposed strategic collaboration with platform ecosystems to scale growth.',
    fullDescription: 'Analyzed digital transformation opportunities for MSMEs by identifying key challenges in adopting technology and proposing strategic solutions to enhance digital adoption, business visibility, and operational efficiency. Included collaboration concepts with platforms like Grab to improve digital presence, customer reach, and business scalability.',
    gradient: 'from-green-700 to-lime-900',
    tags: ['Digital Transformation', 'SME Strategy', 'Market Expansion'],
    challenge: 'Many MSMEs faced low digital readiness, limited online visibility, and unclear transformation priorities to scale in digital channels.',
    solution: 'Designed a strategic roadmap focused on digital onboarding, channel optimization, and ecosystem collaboration to accelerate adoption outcomes.',
    impact: 'Created a practical transformation direction to improve MSME digital visibility, customer reach, and operational effectiveness.',
    tools: ['Porter Five Forces', 'SWOT Analysis', 'Business Model Analysis', 'Market Segmentation', 'Digital Strategy Roadmap'],
    year: '2024',
    date: '05/09/2024 - 18/09/2024',
    deckLink: 'https://drive.google.com/file/d/1B0u5H-GI79jsPGV2BpaAXkmPVSgKgDbP/view?usp=sharing',
    certificationLink: 'https://drive.google.com/file/d/1aJiY6gKm2LaPf-EV9lbUOmiDbsfhYJgN/view?usp=sharing',
    previewImage: '/grab-sme-digital-transformation.png',
  },
  {
    id: '6',
    slug: 'smartfren-s2f-digital-transformation-strategy',
    title: 'Smartfren\'s Digital Transformation Strategy: Boosting Market Share and Enhancing Inclusive Digital Economy with S2F Strategy',
    category: 'Product Management',
    competition: 'Mini Case Competition Billions Universitas Brawijaya 2025',
    shortDescription: 'Developed S2F strategy (FRENZone, SMARTech, SMARTransform) to improve market share and build an inclusive digital ecosystem.',
    fullDescription: 'Conducted a comprehensive business analysis of Smartfren by evaluating market conditions, competitive landscape, and internal capabilities using frameworks and developed a strategic digital transformation plan (S2F Strategy) consisting of FRENZone, SMARTech, and SMARTransform to address market share challenges, combat illegal Wi-Fi competition, and drive inclusive digital ecosystem growth through data-driven and scalable solutions.',
    gradient: 'from-indigo-700 to-blue-900',
    tags: ['Market Analysis', 'Transformation Plan', 'Innovation'],
    challenge: 'Smartfren faced market-share pressure, infrastructure competition from illegal Wi-Fi, and the need for scalable growth in inclusive digital services.',
    solution: 'Formulated the S2F strategic framework with three integrated initiatives that balance market expansion, technology upgrades, and transformation execution.',
    impact: 'Delivered a scalable strategy model to strengthen competitiveness, improve adoption potential, and support inclusive digital economy outcomes.',
    tools: ['SWOT Analysis', 'PESTEL Analysis', 'Competitive Landscape Analysis', 'Internal Capability Analysis', 'Strategic Roadmapping'],
    year: '2025',
    date: '02/08/2025 - 15/08/2025',
    documentLink: 'https://drive.google.com/file/d/1j99HprNzHCboisQBZTNIY7IqfP2VZfqp/view?usp=sharing',
    certificationLink: 'https://drive.google.com/file/d/1OK47erp7HFf_YbzBjspOMOL_YytFXMrz/view?usp=sharing',
    previewImage: '/smartfren-s2f-strategy.jpg',
  },
  {
    id: '7',
    slug: 'telkomsel-nexus-strategy-implementation',
    title: 'Next-generation Enterprise eXcellence Unified System (NEXUS) Strategy Implementation in Telkomsel\'s Goal to Pursue Sustainability Plan 2030',
    category: 'Product Management',
    competition: 'RISE! Business Case Competition 2025',
    shortDescription: 'Built a sustainability-oriented strategy with innovation and business development initiatives backed by data-driven analysis.',
    fullDescription: 'Developed a strategic project focused on innovation and business development by identifying market opportunities, formulating solutions, and delivering a data-driven approach to support sustainable growth and impact.',
    gradient: 'from-red-700 to-orange-900',
    tags: ['Sustainability', 'Strategic Planning', 'Performance'],
    challenge: 'The organization needed a structured strategic approach to align innovation, operations, and sustainability targets toward 2030.',
    solution: 'Developed the NEXUS implementation strategy with clear diagnostics, KPI targets, feasibility checks, and mitigation planning for execution risk.',
    impact: 'Produced an integrated strategy framework that supports innovation execution, measurable growth outcomes, and sustainability alignment.',
    tools: ['McKinsey 7s', 'User Persona', 'BPMN', 'Gap Analysis', 'Root Cause Analysis', 'KPI Measurements & Objective Target', 'Feasibility Analysis', 'Risk Mitigation Analysis'],
    year: '2025',
    date: '31/08/2025 - 26/10/2025',
    deckLink: 'https://drive.google.com/file/d/1CR5gkY3OkOM32I0urNZn3yJ73hqr00-9/view?usp=sharing',
    certificationLink: 'https://drive.google.com/file/d/1MaWapMTsCpAh_8F7YvryY7rvDEUtK8Ck/view?usp=sharing',
    previewImage: '/telkomsel-nexus-strategy.jpg',
  },
  {
    id: '8',
    slug: 'fitfeast',
    title: 'FitFeast',
    category: 'UI/UX Design',
    competition: 'FindIT! 2025 UX Competition by UGM',
    shortDescription: 'Mobile app concept for healthy living with personalized meal planning, AI nutrition scanning, and nutritional tracking in an intuitive UX flow.',
    fullDescription: 'FitFeast is an innovative mobile application concept designed to promote healthy living by providing personalized meal planning and advanced nutritional tracking. Developed as a proposal for the FindIt UGM 2025 UX Competition, the design prioritizes user intuition by implementing classic UX principles such as Parkinson\'s Law, Tesler\'s Law, and Jakob\'s Law to minimize cognitive load. Key features include AI-powered nutrition label scanning, automated meal logging, and BMI-based health assessments, all aimed at helping users maintain a balanced diet through a simple and engaging interface.',
    gradient: 'from-blue-600 to-purple-700',
    tags: ['UX Design', 'Mobile App', 'Health Product'],
    challenge: 'Users need a healthier lifestyle companion that remains simple, low-effort, and easy to understand in day-to-day usage.',
    solution: 'Designed a low-cognitive-load UX with clear meal flows, AI-assisted nutrition scanning, and personalized tracking informed by proven usability principles.',
    impact: 'Delivered a competition-ready UX concept with strong usability rationale and a clear interaction model for healthy habit building.',
    tools: ['User Persona', 'User Journey', 'Flowchart', 'User Testing', 'Survey', 'Interview'],
    year: '2025',
    date: '17/03/2025 - 05/04/2025',
    documentLink: 'https://drive.google.com/file/d/1YNAj-uspgzdh0nIwTKjUawHkP06Nkfmb/view?usp=sharing',
    figmaLink: 'https://www.figma.com/proto/sAQHALZJU2SljfZ0nyF2Su/App-Prototype?page-id=1%3A2&node-id=45-764&p=f&viewport=402%2C178%2C0.05&t=M5iwwSoDCrHd5Mv5-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=43%3A1392&show-proto-sidebar=1',
    previewImage: '/fitfeast-cover-v1.png',
  },
  {
    id: '11',
    slug: 'gawein',
    title: 'GaweIn',
    category: 'UI/UX Design',
    subject: 'II3131 Human and Computer Interaction',
    shortDescription: 'HCI project for safer and more efficient recruitment ecosystem with a simple, confirmed, and trustworthy user journey.',
    fullDescription: 'GaweIn is a Human-Computer Interaction (HCI) project focused on creating a safer and more efficient recruitment ecosystem for informal workers and recruiters in Indonesia. The project utilized deep UX research to address common pain points, such as complex registration steps and a lack of transaction confirmation, resulting in a "Simple and Confirmed" user journey. By emphasizing usability goals like "Safe to Use" and UX goals such as "Helpful," the platform features robust history management for privacy and instant payment notifications to ensure a trustworthy experience for all parties involved.',
    gradient: 'from-sky-700 to-indigo-900',
    tags: ['UX Research', 'Interaction Design', 'Service Platform'],
    challenge: 'Informal worker recruitment flows often feel unsafe and unclear due to weak confirmation loops and complex onboarding.',
    solution: 'Built a UX framework centered on safe interactions, transparent progress states, and confirmation-first transactions supported by user testing.',
    impact: 'Produced a more trustworthy service journey that improves confidence for both workers and recruiters while reducing user friction.',
    tools: ['User Persona', 'Flow & Process', 'UX Goals', 'Usability Goals', 'User Testing', 'Survey', 'Interview', 'Figma'],
    year: '2025',
    date: '16/09/2025 - 22/12/2025',
    deckLink: 'https://drive.google.com/file/d/1ZWJ4UxtMA2BlxsYumBBhRY1PwQQSta7M/view?usp=sharing',
    figmaLink: 'https://www.figma.com/proto/038c1qYxNlG9Xi3BHvO8Ln/GaweIn---Tubes-IMK-Kelompok-6?page-id=725%3A1849&node-id=1349-15347&viewport=1353%2C940%2C0.19&t=fopqWKnUg3AVPWhm-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=1349%3A15347',
    previewImage: '/gawein-original.png',
  },
  {
    id: '12',
    slug: 'anmategra',
    title: 'Anmategra',
    category: 'UI/UX Design',
    subject: 'Kemenkoan PSDM Kabinet KM ITB 2025/2026',
    shortDescription: 'Web-based platform to centralize student activity workflows, profile management, requests, and reporting for administrators.',
    fullDescription: 'Anmategra is a comprehensive web-based platform developed for the Ministry of Synergy and Cadreization (PPSDM) to centralize student activity management and talent tracking. The project involved creating detailed system documentation and user manuals that guide students through end-to-end flows, such as profile management, activity registration, and association requests through an integrated "Inbox" system. By streamlining these administrative processes, the application enhances data accessibility for students while providing administrators with efficient tools to manage reports and technical bug tracking.',
    gradient: 'from-cyan-700 to-blue-900',
    tags: ['UI Design', 'Web Platform', 'System Documentation'],
    challenge: 'Student activity administration was fragmented, causing slow coordination and limited visibility for both students and administrators.',
    solution: 'Designed a centralized platform experience and clear guidance flow for registration, requests, profile updates, and operational reporting.',
    impact: 'Improved process clarity and data accessibility while enabling admins to manage reports and issue tracking more efficiently.',
    tools: ['Figma'],
    year: '2026',
    date: '24/08/2025 - 30/01/2026',
    figmaLink: 'https://www.figma.com/design/UIMtrPlOegJHWQUUYk59oG/Anmategra-Blueprint-2025?node-id=466-7654&t=Bht53MLlLH1s7UjM-1',
    previewImage: '/anmategra-original.png',
  },
  {
    id: '9',
    slug: 'amazon-bestselling-books-reviews-analysis',
    title: 'Amazon Bestselling Books & Reviews Data Analysis',
    category: 'Data & AI',
    subject: 'KU1102 Introduction to Computation',
    shortDescription: 'In-depth analysis of Amazon trending books and reviews to uncover pricing, ranking, and customer preference patterns through visual analytics.',
    fullDescription: 'In this data science project, an in-depth analysis and visualization were conducted on the "Top 100 Trending Books on Amazon" and their corresponding customer reviews. Utilizing Python with the Pandas library and Jupyter Notebook, the project explored correlations between critical elements such as book pricing and ranking to derive meaningful market insights. The final output transformed raw e-commerce data into a structured knowledge base, highlighting the dynamics of consumer preferences and the relationship between user reviews and sales performance.',
    gradient: 'from-cyan-700 to-blue-900',
    tags: ['Data Analysis', 'Visualization', 'Insights'],
    challenge: 'Raw e-commerce data contains noisy signals, making it difficult to identify what truly influences product popularity and market performance.',
    solution: 'Built a notebook-based analysis pipeline to clean, explore, and visualize correlations between ratings, reviews, pricing, and ranking.',
    impact: 'Produced actionable insights on consumer preferences and market dynamics that can guide product positioning and pricing strategy.',
    tools: ['Python', 'Jupiter Notebook', 'Pandas', 'NumPy'],
    year: '2023',
    date: '14/11/2023 - 27/11/2023',
    documentLink: 'https://drive.google.com/file/d/1KJMkiynYSmFa6LOFznTKt13yanVYIhRa/view?usp=sharing',
    previewImage: '/amazon-books-reviews-analysis.jpg',
  },
  {
    id: '13',
    slug: 'airbnb-database-modeling-project',
    title: 'Airbnb Database Modeling Project',
    category: 'Data & AI',
    subject: 'IF2040 Database Modeling',
    shortDescription: 'Comprehensive relational database modeling for Airbnb with ERD design and BCNF normalization to ensure high integrity and low redundancy.',
    fullDescription: 'This project focused on the comprehensive design and modeling of a relational database system for Airbnb as part of the Database Management course. The work involved creating a detailed Entity-Relationship Diagram (ERD) to map complex interactions between users, properties, and reservations, followed by a relational diagram implementation. A key technical focus was ensuring the database reached Boyce-Codd Normal Form (BCNF) to eliminate data redundancy and maintain high integrity across various entities, including payment systems, referral programs, and property management.',
    gradient: 'from-sky-700 to-cyan-900',
    tags: ['Database Design', 'Data Modeling', 'Optimization'],
    challenge: 'Complex entity relationships in a marketplace platform can create redundancy and inconsistency without rigorous schema design.',
    solution: 'Developed an ERD-to-relational workflow with normalization and dependency checks to achieve a robust BCNF-compliant schema.',
    impact: 'Delivered a scalable database structure with stronger data integrity, reduced redundancy, and clearer system relationships.',
    tools: ['ERD', 'BCNF', 'Relational Model', 'Database Normalization', 'Functional Dependency', 'MySQL'],
    year: '2024',
    date: '06/11/2024 - 16/12/2024',
    documentLink: 'https://drive.google.com/file/d/1IeTua4GkndnTsklInTdfzdrlievexoHD/view?usp=sharing',
    previewImage: '/airbnb-database-modeling.jpg',
  },
  {
    id: '14',
    slug: 'bin-packing-local-search-solver',
    title: 'Bin Packing Problem Solver using Local Search Algorithms',
    category: 'Data & AI',
    subject: 'IF3070 Basic Artificial Intelligence',
    shortDescription: 'AI optimization project comparing local search algorithms to solve bin packing efficiently with near-optimal allocation results.',
    fullDescription: 'This Artificial Intelligence project addressed the "Bin Packing Problem" - an optimization challenge involving the efficient packing of items into the minimum number of containers. The project implemented and compared various Local Search algorithms, including Steepest Ascent Hill-Climbing, Stochastic Hill-Climbing, and Simulated Annealing. By designing specific objective functions and data representations, the system was able to navigate complex search spaces to find optimal or near-optimal solutions for resource allocation and logistical efficiency.',
    gradient: 'from-indigo-700 to-blue-900',
    tags: ['Artificial Intelligence', 'Optimization', 'Algorithmic Thinking'],
    challenge: 'Searching for optimal packing arrangements becomes computationally expensive as item combinations and constraints grow rapidly.',
    solution: 'Implemented multiple local-search variants and objective functions to efficiently explore solution spaces and compare convergence behavior.',
    impact: 'Generated strong near-optimal packing solutions and clear algorithm comparisons useful for practical resource allocation scenarios.',
    tools: ['Python', 'Genetic Algorithm', 'Hill Climbing', 'Simulated Annealing', 'Matplotlib', 'JSON', 'Random', 'Math'],
    year: '2025',
    date: '06/10/2025 - 30/10/2025',
    documentLink: 'https://drive.google.com/file/d/1N4ITDIZzvLFa_NsT5_CDpUq5JlXyjNYF/view?usp=sharing',
    githubLink: 'https://github.com/princessfaazzahra/Tugas-Besar-AI-IF3070---Ooga-',
    previewImage: '/bin-packing-local-search.jpg',
  },
  {
    id: '15',
    slug: 'fraud-detection-machine-learning-implementation',
    title: 'Machine Learning Implementation for Fraud Detection',
    category: 'Data & AI',
    subject: 'IF3070 Basic Artificial Intelligence',
    shortDescription: 'Machine learning implementation for fraud detection using CART and Logistic Regression with full EDA and model evaluation workflow.',
    fullDescription: 'This project involved the application of advanced Machine Learning algorithms to identify fraudulent activities within a specialized dataset. The implementation focused on building and evaluating a Classification and Regression Tree (CART) model and Logistic Regression to achieve high predictive accuracy. The end-to-end workflow included rigorous data cleaning, Exploratory Data Analysis (EDA) using Python, and performance validation to ensure the models could effectively distinguish between legitimate and fraudulent transactions in real-world scenarios.',
    gradient: 'from-violet-700 to-purple-900',
    tags: ['Machine Learning', 'Classification', 'Fraud Detection'],
    challenge: 'Fraud datasets are often imbalanced and noisy, making it difficult to maintain both high detection sensitivity and precision.',
    solution: 'Built an end-to-end ML pipeline with robust preprocessing, EDA, feature handling, and comparative model evaluation.',
    impact: 'Demonstrated reliable fraud classification performance and a reproducible workflow ready for further production hardening.',
    tools: ['Python', 'Jupyter Notebook', 'Pandas', 'NumPy', 'Scikit-learn', 'CART', 'Logistic Regression', 'LabelEncoder', 'Matplotlib', 'Seaborn'],
    year: '2025',
    date: '25/11/2025 - 13/12/2025',
    documentLink: 'https://drive.google.com/file/d/1cBEqn6tQxVnXuZRaL4HNYZWzyswbtVoT/view?usp=sharing',
    githubLink: 'https://github.com/princessfaazzahra/Tugas-Besar-2-IF3070---Ooga',
    previewImage: '/fraud-detection-ml.jpg',
  },
  {
    id: '16',
    slug: 'physphere-web-based-virtual-physics-lab',
    title: 'PhySphere: Web-Based Virtual Physics Lab',
    category: 'Others',
    subject: 'II3140 Web and Mobile Application Development',
    shortDescription: 'Comprehensive web-based LMS for studying simple harmonic motion with an interactive virtual physics lab and progress-based learning.',
    fullDescription: 'PhySphere is a comprehensive web-based Learning Management System (LMS) designed to facilitate the study of Simple Harmonic Motion (SHM). The platform features an interactive virtual laboratory built with HTML5 Canvas, allowing students to simulate experiments by adjusting variables such as mass, string length, and gravity. It also includes structured learning modules, progress tracking, and data-driven quizzes. The web implementation serves as a centralized administrative and educational hub with Supabase-based real-time database management and authentication.',
    gradient: 'from-violet-700 to-indigo-900',
    tags: ['Web Application', 'Learning Platform', 'Interactive Simulation'],
    challenge: 'Learning abstract SHM concepts is difficult without practical experimentation access and structured digital guidance.',
    solution: 'Built a web LMS with interactive simulation, modular learning content, and integrated assessment and progress tracking.',
    impact: 'Improved conceptual understanding and engagement through hands-on virtual experimentation in a centralized learning environment.',
    tools: ['HTML5', 'CSS3', 'JavaScript (ES6+)', 'Tailwind CSS', 'HTML5 Canvas', 'Supabase', 'PostgreSQL', 'Vercel', 'Google Auth API'],
    year: '2025',
    date: '20/10/2025 - 07/11/2025',
    documentLink: 'https://drive.google.com/file/d/16MSb5Q7chekGIKi7eT6f_EaTe0_F83oR/view?usp=sharing',
    githubLink: 'https://github.com/fhatikaadr/Tugas-Virtual-Lab-PAWM-Kelompok-8',
    previewImage: '/physphere-web-based.png',
  },
  {
    id: '17',
    slug: 'physphere-mobile-based-virtual-physics-lab',
    title: 'PhySphere: Mobile-Based Virtual Physics Lab',
    category: 'Others',
    subject: 'II3140 Web and Mobile Application Development',
    shortDescription: 'High-performance React Native mobile app for portable virtual physics experiments with synchronized cross-platform learning data.',
    fullDescription: 'PhySphere Mobile is a high-performance mobile application developed with React Native and Expo for portable learning and on-the-go experimentation. It preserves the core virtual laboratory and interactive quiz features while prioritizing touch responsiveness and accessibility. Students can run simulations and complete assessments directly from their smartphones. The app is integrated with the same Supabase backend as the web platform to provide seamless cross-platform data synchronization.',
    gradient: 'from-fuchsia-700 to-rose-900',
    tags: ['Mobile Application', 'Educational Technology', 'Cross-Platform'],
    challenge: 'Students needed flexible access to simulation-based learning outside desktop environments without losing continuity.',
    solution: 'Developed a mobile-first virtual lab and quiz flow with synchronized backend services for seamless multi-device usage.',
    impact: 'Increased accessibility and learning continuity by enabling simulation and assessment workflows directly on mobile devices.',
    tools: ['HTML5', 'CSS3', 'JavaScript (ES6+)', 'React Native', 'Expo Go', 'Tailwind CSS', 'HTML5 Canvas', 'Supabase', 'Vercel'],
    year: '2026',
    date: '10/12/2025 - 05/01/2026',
    documentLink: 'https://drive.google.com/file/d/1Ilvg-fPX9he9oXW-o95RH1l3cdaiHY0X/view?usp=sharing',
    githubLink: 'https://github.com/florecita24/Tugas-Virtual-Lab-PAWM-Kelompok-8-PhySphere-Mobile',
    previewImage: '/physphere-mobile-based.png',
  },
  {
    id: '18',
    slug: 'purrmart-cli-ecommerce-simulation',
    title: 'PURRMART',
    category: 'Others',
    subject: 'IF2111 Algorithms and Data Structures of IST',
    shortDescription: 'CLI-based e-commerce simulation in C implementing ADTs for item management, work challenges, and virtual economy workflows.',
    fullDescription: 'PURRMART is a Command-Line Interface (CLI) system developed in C that simulates an e-commerce ecosystem. The application enables users to manage a virtual store by listing, adding, and removing items while performing simulated work challenges to earn virtual currency. The implementation emphasizes practical use of Abstract Data Types (ADT), including dynamic arrays, queues, and character/word machines for efficient data handling and file processing.',
    gradient: 'from-orange-700 to-red-900',
    tags: ['CLI Application', 'Data Structures', 'System Simulation'],
    challenge: 'Building a robust text-based commerce simulation requires efficient data handling, reliable parsing, and modular state management.',
    solution: 'Implemented ADT-driven architecture with command workflows, queue-based activities, and consistent file processing modules.',
    impact: 'Delivered a stable simulation environment that demonstrates applied algorithmic thinking and scalable CLI system structure.',
    tools: ['C', 'Makefile', 'Abstract Data Types (ADT)', 'Compiler Flags', 'GCC', 'GNU Make', 'GDB'],
    year: '2024',
    date: '11/11/2024 - 22/12/2024',
    documentLink: 'https://drive.google.com/file/d/1-h3odwTrqtz1Srpst1vrZuZyav4voY1t/view?usp=sharing',
    githubLink: 'https://github.com/RylRizqi16/Tubes_IF2111_02_10',
    previewImage: '/purrmart-original.jpg',
  },
  {
    id: '19',
    slug: 'the-owca-adventure',
    title: 'The OWCA Adventure',
    category: 'Others',
    subject: 'IF1210 Basic Programming',
    shortDescription: 'Terminal-based Python monster-battle game with ASCII visuals, inventory mechanics, and virtual shop interactions.',
    fullDescription: 'The OWCA Adventure is a terminal-based monster-battle simulation game developed in Python with a procedural and functional programming focus. Inspired by Agent P lore, players capture, train, and battle monsters to protect Danville from Dr. Asep Spakbor\'s creations. The game includes ASCII-art interfaces, monster data management, potion inventory mechanics, and a virtual shop that models basic in-game economic transactions.',
    gradient: 'from-amber-700 to-orange-900',
    tags: ['Game Development', 'Programming Fundamentals', 'Terminal Interface'],
    challenge: 'Creating engaging gameplay in a terminal-only environment requires strong logic structure and clear state-driven interactions.',
    solution: 'Designed modular gameplay loops for battle, inventory, progression, and data handling with ASCII-based UI feedback.',
    impact: 'Produced a complete playable CLI game that demonstrates programming fundamentals, data handling, and interaction design basics.',
    tools: ['Python', 'CSV', 'ASCII Art'],
    year: '2024',
    date: '26/04/2024 - 18/05/2024',
    documentLink: 'https://drive.google.com/file/d/1EwVFFGh_AMIalL7sw1x90pmjSHyhTgQM/view?usp=sharing',
    sourceCodeLink: 'https://drive.google.com/file/d/19OkGfDKk_h-6AOevRBqCfT_Rp6V6x-PE/view?usp=sharing',
    previewImage: '/owca-adventure-original.jpg',
  },
  {
    id: '20',
    slug: 'spakbor-hills',
    title: 'Spakbor Hills',
    category: 'Others',
    subject: 'IF2010 Object Oriented Programming',
    shortDescription: 'Java CLI farming simulation with OOP architecture, concurrency handling, and dynamic world systems for strategy-based gameplay.',
    fullDescription: 'Spakbor Hills is a Java-based farming simulation game played via Command-Line Interface, applying Object-Oriented Programming principles, concurrency, and design patterns such as Observer. Players manage farming activities including tilling, planting, fishing, and cooking while interacting with NPCs to reach milestones like wealth accumulation and marriage. The game includes dynamic time and weather systems that directly affect strategy and resource planning.',
    gradient: 'from-emerald-700 to-green-900',
    tags: ['Object-Oriented Programming', 'Game Simulation', 'Software Design'],
    challenge: 'Complex simulation mechanics required maintainable object design and coordinated runtime updates for world-state changes.',
    solution: 'Implemented object-oriented domain models, event-driven updates, and CLI gameplay systems with modular responsibilities.',
    impact: 'Delivered a feature-rich simulation game that demonstrates strong OOP application and scalable gameplay architecture.',
    tools: ['Java', 'Gradle', 'Gson (v2.10.1)', 'JUnit Jupiter (v5.9.0)'],
    year: '2025',
    date: '16/04/2025 - 01/06/2025',
    documentLink: 'https://drive.google.com/file/d/13nfmf7rxxlepBQu-NRpNOwh80lsQAOC1/view?usp=sharing',
    githubLink: 'https://github.com/furhuruhun/Tubes-OOP-K02-G03',
    previewImage: '/spakbor-hills-original.jpg',
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find(p => p.slug === slug);
}
